[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

startup_mode = "Maximized"

decorations = "Buttonless"
opacity = 1.0
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14.0
