[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
dynamic_padding = true

startup_mode = "Maximized"
decorations = "Full"
opacity = 1.0
blur = true

[colors]
# Background color from "Adapta-Nokto" theme
primary.background = "#222d32"

[font]
size = 14.0

normal.family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
# Open new windows at the same dir
{ key = "Enter", mods = "Command|Shift", action = "CreateNewWindow" },
# Scroll keybindings
{ key = "PageUp", mods = "None", action = "ScrollLineUp" },
{ key = "PageDown", mods = "None", action = "ScrollLineDown" },
{ key = "PageUp", mods = "Shift", action = "ScrollHalfPageUp" },
{ key = "PageDown", mods = "Shift", action = "ScrollHalfPageDown" },
{ key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp" },
{ key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown" },
]
